//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_remote : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Play
        {
            get
            {
                return SteamVR_Actions.remote_Play;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pause
        {
            get
            {
                return SteamVR_Actions.remote_Pause;
            }
        }
        
        public virtual SteamVR_Action_Boolean Seek
        {
            get
            {
                return SteamVR_Actions.remote_Seek;
            }
        }
        
        public virtual SteamVR_Action_Vibration NewAction
        {
            get
            {
                return SteamVR_Actions.remote_NewAction;
            }
        }
    }
}
